# Generated by Django 3.2.22 on 2023-10-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231026_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
