# Generated by Django 3.2.22 on 2023-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_version_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
