# Generated by Django 3.2.22 on 2023-10-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_precio_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='precio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
